"""add active budget uniqueness

Revision ID: 2a56078d6f32
Revises: aaae8570c7cf
Create Date: 2026-06-30 15:28:31.087687
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '2a56078d6f32'
down_revision: str | None = 'aaae8570c7cf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_budgets_user_category_period', table_name='budgets')
    op.create_index('uq_budgets_active_user_category_period', 'budgets', ['user_id', 'category_id', 'year', 'month'], unique=True, postgresql_where=sa.text('is_active IS true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_budgets_active_user_category_period', table_name='budgets', postgresql_where=sa.text('is_active IS true'))
    op.create_index('ix_budgets_user_category_period', 'budgets', ['user_id', 'category_id', 'year', 'month'], unique=False)
    # ### end Alembic commands ###
