"""add transaction soft delete

Revision ID: 2bea77556a4a
Revises: 9b1e62c0ea99
Create Date: 2026-06-26 15:02:29.042374
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '2bea77556a4a'
down_revision: str | None = '9b1e62c0ea99'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('transactions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'deleted_at')
    op.drop_column('transactions', 'is_active')
    # ### end Alembic commands ###
