"""create budgets

Revision ID: aaae8570c7cf
Revises: 2bea77556a4a
Create Date: 2026-06-30 15:27:58.045564
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'aaae8570c7cf'
down_revision: str | None = '2bea77556a4a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('limit_amount > 0', name='ck_budgets_limit_amount_positive'),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='ck_budgets_month_range'),
    sa.CheckConstraint('year >= 2000 AND year <= 2100', name='ck_budgets_year_range'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_budgets_category_id', 'budgets', ['category_id'], unique=False)
    op.create_index('ix_budgets_period', 'budgets', ['year', 'month'], unique=False)
    op.create_index('ix_budgets_user_category_period', 'budgets', ['user_id', 'category_id', 'year', 'month'], unique=False)
    op.create_index('ix_budgets_user_id', 'budgets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_budgets_user_id', table_name='budgets')
    op.drop_index('ix_budgets_user_category_period', table_name='budgets')
    op.drop_index('ix_budgets_period', table_name='budgets')
    op.drop_index('ix_budgets_category_id', table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
